### ISSUE TITLE
Add a small README with info on how to configure and use chub

### ISSUE THREAD

**Issue by CamilleScholtz** [vchimishuk/chub#2]
I know this program is probably still in alpha, beta or whatever you want to call it, but it would be nice :)

**Comment by vchimishuk** [comment]
Unfortunately, it is almost unusable for now. But you are right. I'll add it. Thank you.

**Comment by vchimishuk** [comment]
Finally added [README.md](https://github.com/vchimishuk/chub/blob/master/README.md) after so many years.
Also added [FAQ](https://github.com/vchimishuk/chub/wiki/FAQ) wiki page.
 
@CamilleScholtz, thanks for your interest.
